src/Entity/Contrat.php
<?php

namespace App\Entity;

use App\Repository\ContratRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ContratRepository::class)
 */
class Contrat
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull
     */
    private $num_contrat;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull
     */
    private $nom_user;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull
     */
    private $prenom_user;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull
     * @Assert\Length(
     *      min = 8,
     *      max = 8,
     *      minMessage = "Your number must be at least {{ limit }} characters long",
     *      maxMessage = "Your number cannot be longer than {{ limit }} characters"
     * )
     */

    private $num_tel;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Length(
     *      min = 4,
     *      max = 4,
     *      minMessage = "Your code postal must be at least {{ limit }} characters long",
     *      maxMessage = "Your code postal cannot be longer than {{ limit }} characters"
     * )
     * @Assert\NotNull
     */
    private $code_postal;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *      min = 4,
     *      max = 10,
     *      minMessage = "Your ville name must be at least {{ limit }} characters long",
     *      maxMessage = "Your ville name cannot be longer than {{ limit }} characters"
     * )
     * @Assert\NotNull
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull
     */
    private $destinataire;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type_contrat;

    /**
     * @ORM\Column(type="date")
     * @Assert\Date
     * @var string A "Y-m-d" formatted value
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nature_contart;

    /**
     * @ORM\ManyToOne(targetEntity=Contrat::class, inversedBy="DemandeContratRepository")
     */
    private $contrat;

    /**
     * @ORM\ManyToOne(targetEntity=DemandeContart::class, inversedBy="contrat")
     */
    private $demandeContart;


    public function __construct()
    {
        $this->DemandeContratRepository = new ArrayCollection();
    }

    /**
     * @return integer
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getNumContrat(): ?string
    {
        return $this->num_contrat;
    }

    /**
     * @param string $num_contrat
     * @Contrat
     */
    public function setNumContrat(string $num_contrat): self
    {
        $this->num_contrat = $num_contrat;

        return $this;
    }

    /**
     * @return string
     */
    public function getNomUser(): ?string
    {
        return $this->nom_user;
    }

    /**
     * @param string $nom_user
     * @return Contrat
     */
    public function setNomUser(string $nom_user): self
    {
        $this->nom_user = $nom_user;

        return $this;
    }

    /**
     * @return string
     */
    public function getPrenomUser(): ?string
    {
        return $this->prenom_user;
    }

    /**
     * @param string $prenom_user
     * @return Contrat
     */
    public function setPrenomUser(string $prenom_user): self
    {
        $this->prenom_user = $prenom_user;

        return $this;
    }

    /**
     * @return string
     */
    public function getNumTel(): ?string
    {
        return $this->num_tel;
    }

    /**
     * @param string $num_tel
     * @return Contrat
     */
    public function setNumTel(string $num_tel): self
    {
        $this->num_tel = $num_tel;

        return $this;
    }

    /**
     * @return integer
     */
    public function getCodePostal(): ?int
    {
        return $this->code_postal;
    }

    /**
     * @param int $code_postal
     * @return Contrat
     */
    public function setCodePostal(int $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    /**
     * @return string
     */
    public function getVille(): ?string
    {
        return $this->ville;
    }

    /**
     * @param string $ville
     * @return Contrat
     */
    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    /**
     * @return string
     */
    public function getDestinataire(): ?string
    {
        return $this->destinataire;
    }

    /**
     * @param string $destinataire
     * @return Contrat
     */
    public function setDestinataire(string $destinataire): self
    {
        $this->destinataire = $destinataire;

        return $this;
    }

    /**
     * @return string
     */
    public function getTypeContrat(): ?string
    {
        return $this->type_contrat;
    }

    /**
     * @param string $type_contrat
     * @return Contrat
     */
    public function setTypeContrat(string $type_contrat): self
    {
        $this->type_contrat = $type_contrat;

        return $this;
    }

    /**
     * @return \DateTimeInterface|null
     */
    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    /**
     * @param \DateTimeInterface $date
     * @return Contrat
     */
    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    /**
     * @return string
     */
    public function getNatureContart(): ?string
    {
        return $this->nature_contart;
    }

    /**
     * @param string $nature_contart
     * @return Contrat
     */
    public function setNatureContart(string $nature_contart): self
    {
        $this->nature_contart = $nature_contart;

        return $this;
    }


    public function getContrat(): ?self
    {
        return $this->contrat;
    }

    public function setContrat(?self $contrat): self
    {
        $this->contrat = $contrat;

        return $this;
    }

    public function getDemandeContart(): ?DemandeContart
    {
        return $this->demandeContart;
    }

    public function setDemandeContart(?DemandeContart $demandeContart): self
    {
        $this->demandeContart = $demandeContart;

        return $this;
    }


    public function __toString()
    {
        return $this->num_contrat;


    }
}

src/Form/ContratType.php
<?php

namespace App\Form;

use App\Entity\Contrat;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContratType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('num_contrat')
            ->add('nom_user')
            ->add('prenom_user')
            ->add('num_tel')
            ->add('code_postal')
            ->add('ville')
            ->add('destinataire')
            ->add('type_contrat')
            ->add('date')
            ->add('nature_contart')
            ->add('contrat')
            ->add('demandeContart')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Contrat::class,
        ]);
    }
}

src/Controller/ContratController.php
<?php

namespace App\Controller;

use App\Entity\Contrat;
use App\Form\ContratType;
use App\Repository\ContratRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/contrat")
 */
class ContratController extends AbstractController
{
    /**
     * @Route("/", name="contrat_index", methods={"GET"})
     */
    public function index(ContratRepository $contratRepository): Response
    {
        return $this->render('contrat/index.html.twig', [
            'contrats' => $contratRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="contrat_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $contrat = new Contrat();
        $form = $this->createForm(ContratType::class, $contrat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($contrat);
            $entityManager->flush();

            return $this->redirectToRoute('contrat_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('contrat/new.html.twig', [
            'contrat' => $contrat,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="contrat_show", methods={"GET"})
     */
    public function show(Contrat $contrat): Response
    {
        return $this->render('contrat/show.html.twig', [
            'contrat' => $contrat,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="contrat_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Contrat $contrat, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ContratType::class, $contrat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('contrat_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('contrat/edit.html.twig', [
            'contrat' => $contrat,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="contrat_delete", methods={"POST"})
     */
    public function delete(Request $request, Contrat $contrat, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$contrat->getId(), $request->request->get('_token'))) {
            $entityManager->remove($contrat);
            $entityManager->flush();
        }

        return $this->redirectToRoute('contrat_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/contrat/_delete_form.html.twig
<form method="post" action="{{ path('contrat_delete', {'id': contrat.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ contrat.id) }}">
    <button class="btn">Delete</button>
</form>

templates/contrat/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/contrat/edit.html.twig
{% extends 'base-front.html.twig' %}

{% block title %}Edit Contrat{% endblock %}

{% block body %}
    <h1>Edit Contrat</h1>

    {{ include('contrat/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('contrat_index') }}">back to list</a>

    {{ include('contrat/_delete_form.html.twig') }}
{% endblock %}

templates/contrat/index.html.twig
{% extends 'base-front.html.twig' %}

{% block title %}Contrat index{% endblock %}

{% block body %}
    <h1>Contrat index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Num_contrat</th>
                <th>Nom_user</th>
                <th>Prenom_user</th>
                <th>Num_tel</th>
                <th>Code_postal</th>
                <th>Ville</th>
                <th>Destinataire</th>
                <th>Type_contrat</th>
                <th>Date</th>
                <th>Nature_contart</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for contrat in contrats %}
            <tr>
                <td>{{ contrat.id }}</td>
                <td>{{ contrat.numContrat }}</td>
                <td>{{ contrat.nomUser }}</td>
                <td>{{ contrat.prenomUser }}</td>
                <td>{{ contrat.numTel }}</td>
                <td>{{ contrat.codePostal }}</td>
                <td>{{ contrat.ville }}</td>
                <td>{{ contrat.destinataire }}</td>
                <td>{{ contrat.typeContrat }}</td>
                <td>{{ contrat.date ? contrat.date|date('Y-m-d') : '' }}</td>
                <td>{{ contrat.natureContart }}</td>
                <td>
                    <a href="{{ path('contrat_show', {'id': contrat.id}) }}">show</a>
                    <a href="{{ path('contrat_edit', {'id': contrat.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('contrat_new') }}">Create new</a>
{% endblock %}

templates/contrat/new.html.twig
{% extends 'base-front.html.twig' %}

{% block title %}New Contrat{% endblock %}

{% block body %}
    <h1>Create new Contrat</h1>

    {{ include('contrat/_form.html.twig') }}

    <a href="{{ path('contrat_index') }}">back to list</a>
{% endblock %}

templates/contrat/show.html.twig
{% extends 'base-front.html.twig' %}

{% block title %}Contrat{% endblock %}

{% block body %}
    <h1>Contrat</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ contrat.id }}</td>
            </tr>
            <tr>
                <th>Num_contrat</th>
                <td>{{ contrat.numContrat }}</td>
            </tr>
            <tr>
                <th>Nom_user</th>
                <td>{{ contrat.nomUser }}</td>
            </tr>
            <tr>
                <th>Prenom_user</th>
                <td>{{ contrat.prenomUser }}</td>
            </tr>
            <tr>
                <th>Num_tel</th>
                <td>{{ contrat.numTel }}</td>
            </tr>
            <tr>
                <th>Code_postal</th>
                <td>{{ contrat.codePostal }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ contrat.ville }}</td>
            </tr>
            <tr>
                <th>Destinataire</th>
                <td>{{ contrat.destinataire }}</td>
            </tr>
            <tr>
                <th>Type_contrat</th>
                <td>{{ contrat.typeContrat }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ contrat.date ? contrat.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Nature_contart</th>
                <td>{{ contrat.natureContart }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('contrat_index') }}">back to list</a>

    <a href="{{ path('contrat_edit', {'id': contrat.id}) }}">edit</a>

    {{ include('contrat/_delete_form.html.twig') }}
{% endblock %}